apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sae
resources:
  - ../../bases
  - ./ingress.yaml
images:
  - name: sae_api_image
    newName: harbor.server.dylanbattig.fr/private/sae_api # {"$imagepolicy": "flux-system:sae-api:name"}
    newTag: main # {"$imagepolicy": "flux-system:sae-api:tag"}
