apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sae
resources:
  - ../../bases
  - ./ingress.yaml
images:
  - name: sae_api_image
    newName: harbor.server.dylanbattig.fr/private/sae-api # {"$imagepolicy": "flux-system:sae-api:name"}
    newTag: main-f9038bfac9253f105f2d3e5e4236c929f3134bd6-12 # {"$imagepolicy": "flux-system:sae-api:tag"}
