apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sae
resources:
  - ../../bases
  - ./ingress.yaml
images:
  - name: sae_api_image
    newName: harbor.server.dylanbattig.fr/private/sae-api # {"$imagepolicy": "flux-system:sae-api:name"}
    newTag: main-fc5e763afb8a4aaa772cc69368454a8224f97ffe-11 # {"$imagepolicy": "flux-system:sae-api:tag"}
