apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sae
resources:
  - ../../bases
  - ./ingress.yaml
images:
  - name: sae_api_image
    newName: harbor.server.dylanbattig.fr/private/sae-api # {"$imagepolicy": "flux-system:sae-api:name"}
    newTag: main-ea900f6c83258a81a21b426399deb23b805a0efe-9 # {"$imagepolicy": "flux-system:sae-api:tag"}
