name: Docker build and push Workflow

on:
  workflow_call:
    inputs:
      registry:
        description: "Docker registry url"
        type: string
        required: true
      
      context:
        description: "Docker context"
        type: string
        required: false
        default: .

      dockerfile:
        description: "Dockerfile"
        type: string
        required: false
        default: Dockerfile

      image-name:
        description: "Docker image name"
        type: string
        required: false
        default: ${{ github.repository }}

      image-tag:
        description: "Docker image tag"
        type: string
        required: false
        default: ${{ github.sha }}-${{ github.run_number }}
    secrets:
      REGISTRY_TOKEN:
        description: "Docker registry token"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ inputs.registry }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: robot$github
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}

          push: ${{ github.event_name != 'pull_request' }}
          
          tags: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}

          cache-from: type=gha
          cache-to: type=gha,mode=max